name: flutter_weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_size_text_plus: ^3.0.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.2.0
  location: ^5.0.3
  permission_handler: ^11.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - .env
  uses-material-design: true
